Optimize multiplyBasisFunction by caching math operations
woltapp/blurhash pull request #150
Opened 2021-12-08 13:44 UTC by Connormiha

I have optimized some operations to avoid re-computation.

2022-07-14 09:45 UTC, Thisen requested changes
A small change, then LGTM :)

2022-07-14 09:45 UTC, Thisen commented on TypeScript/src/encode.ts
> +      const basePixelIndex = bytesPerPixelX + (y * bytesPerRow);
Can you remove the parenteses?

2022-07-14 09:53 UTC, Connormiha commented on TypeScript/src/encode.ts
> +      const basePixelIndex = bytesPerPixelX + (y * bytesPerRow);
Done

2022-07-15 06:38 UTC, Thisen approved these changes
Thanks for you contribution :)

2022-07-15 06:38 UTC, merged